# Generated by Django 5.0.4 on 2026-01-10 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('encerrado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_tombamento', models.CharField(db_index=True, max_length=30, unique=True)),
                ('nome', models.CharField(blank=True, max_length=150)),
                ('empenho', models.CharField(blank=True, max_length=50)),
                ('campus_origem', models.CharField(blank=True, max_length=50)),
                ('nota_fiscal', models.CharField(blank=True, max_length=30)),
                ('data_entrada', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TombamentoAnual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='core.ambiente')),
            ],
            options={
                'unique_together': {('nome', 'ambiente')},
            },
        ),
        migrations.CreateModel(
            name='ItemInventariado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ok', 'Correto'), ('fora_do_lugar', 'Fora do lugar'), ('nao_encontrado', 'Não encontrado')], default='nao_encontrado', max_length=20)),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.inventario')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras_inventario', to='core.item')),
                ('sala_encontrada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sala')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='sala_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='core.sala'),
        ),
        migrations.CreateModel(
            name='ItemTombado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movido', models.BooleanField(default=False)),
                ('lido_em', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras_tombamento', to='core.item')),
                ('sala_encontrada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sala')),
                ('tombamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.tombamentoanual')),
            ],
        ),
        migrations.AddConstraint(
            model_name='iteminventariado',
            constraint=models.UniqueConstraint(fields=('inventario', 'item'), name='unique_item_por_inventario'),
        ),
        migrations.AddConstraint(
            model_name='itemtombado',
            constraint=models.UniqueConstraint(fields=('item', 'tombamento'), name='unique_item_por_tombamento'),
        ),
    ]
