# Generated by Django 5.0.4 on 2026-01-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminventariado',
            name='status',
            field=models.CharField(choices=[('ok', 'Correto'), ('fora_do_lugar', 'Fora do lugar'), ('movido', 'Movido'), ('nao_encontrado', 'Não encontrado')], default='nao_encontrado', max_length=20),
        ),
    ]
