# Generated by Django 5.0.4 on 2026-01-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_iteminventariado_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminventariado',
            name='status',
            field=models.CharField(choices=[('ok', 'Correto'), ('fora_do_lugar', 'Fora do lugar'), ('movido', 'Movido'), ('mantido_oficial', 'Mantido na sala oficial'), ('nao_encontrado', 'Não encontrado')], default='nao_encontrado', max_length=20),
        ),
    ]
