# Generated by Django 5.0.4 on 2026-01-25 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_iteminventariado_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminventariado',
            name='resolvido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iteminventariado',
            name='resolvido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='iteminventariado',
            name='status',
            field=models.CharField(choices=[('correto', 'Correto'), ('fora_do_lugar', 'Fora do lugar'), ('movido', 'Movido para sala encontrada'), ('mantido_oficial', 'Mantido na sala origem'), ('nao_encontrado', 'Não encontrado')], default='nao_encontrado', max_length=20),
        ),
    ]
