# Generated by Django 5.0.4 on 2026-02-14 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_iteminventariado_resolvido_em_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminventariado',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leituras_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='iteminventariado',
            name='resolvido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leituras_resolvidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
