# Generated by Django 5.0.4 on 2026-06-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_iteminventariado_registrado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminventariado',
            name='status',
            field=models.CharField(choices=[('ok', 'Correto'), ('fora_do_lugar', 'Fora do lugar'), ('movido', 'Movido para sala encontrada'), ('mantido_oficial', 'Mantido na sala origem'), ('nao_encontrado', 'Não encontrado')], default='nao_encontrado', max_length=20),
        ),
    ]
